services:
    db:
        image: postgres:17
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - .env
    redis:
        image: redis
        container_name: redis-server
        ports:
            - "6379:6379"
    django-web:
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: django-petproject

        ports:  
            - "8000:8000"
        depends_on:
            - db
            - redis
        volumes:
            - ./static:/app/static
            - ./staticfiles:/app/staticfiles
            - ./staticfiles_data:/app/staticfiles
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            DEBUG: ${DEBUG}
            DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USERNAME: ${DATABASE_USERNAME}
        
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: ${DATABASE_HOST}
            DATABASE_PORT: ${DATABASE_PORT}
        env_file:
            - .env
volumes:
    postgres_data:
    staticfiles_data: