# Generated by Django 5.1.4 on 2025-01-03 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='yoda', max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=5)]),
            preserve_default=False,
        ),
    ]
