# Generated by Django 5.1.4 on 2025-01-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title', 'description'], name='idx_title_description'),
        ),
    ]
