name: Deploy to Server

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            - name: Log in to DockerHub
              env:
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

            - name: Pull Project From GitHub
              run: |
                  sudo rm -rf petproject

                  mkdir petproject
                  cd petproject

                  git clone https://github.com/muhammadyusuf799/petproject.git .

            - name: Build and Push Docker Image
              run: |
                  IMAGE_TAG=$(git rev-parse --short HEAD)
                  docker build -t masteryoda727/petproject:$IMAGE_TAG .
                  docker push masteryoda727/petproject:$IMAGE_TAG

            - name: SSH to Server and Deploy
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      cd /home/muhammad/petproject

                      IMAGE_TAG=$(git rev-parse --short HEAD)
                      sudo docker pull masteryoda727/petproject:$IMAGE_TAG

                      sudo docker compose down
                      sudo docker compose up -d
                      sudo docker exec django-petproject python manage.py collectstatic --noinput
                      sudo docker exec django-petproject python manage.py migrate
